const colors = {
    WHITE: '#FFFFFF',
    BLACK: '#000000',

    DARK_GRAY: '#2B2730',
    PINK: '#E966A0',
    DARK_PURPLE: '#6554AF',
    LIGHT_PURPLE: '#9575DE',

    LIGHT_BRIGHT_GREEN: '#C8E4B2',
    LIGHT_SAGE_GREEN: '#9ED2BE',
    DARK_SAGE_GREEN: '#7EAA92',
    BEIGE: '#FFD9B7',

    WHITE_PINK: '#F9F5F6',
    WHITE_PINK2: '#F8E8EE',
    LIGHT_PASTEL_PINK: '#FDCEDF',
    DARK_PASTEL_PINK: '#F2BED1'


  };
  
  export { colors };